/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE, type Song, type Album, type SocialProfile } from "./declarations/backend.did";
export type { Song, Album, SocialProfile } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    getSongs(): Promise<Song[]>;
    addSong(song: Song): Promise<void>;
    deleteSong(id: string): Promise<void>;
    getAlbums(): Promise<Album[]>;
    addAlbum(album: Album): Promise<void>;
    deleteAlbum(id: string): Promise<void>;
    getSocialProfiles(): Promise<SocialProfile[]>;
    addSocialProfile(profile: SocialProfile): Promise<void>;
    updateSocialProfile(profile: SocialProfile): Promise<void>;
    deleteSocialProfile(id: string): Promise<void>;
    getLiveUrl(): Promise<string>;
    setLiveUrl(url: string): Promise<void>;
    clearLiveUrl(): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(_secret: string): Promise<void> {}
    async getSongs(): Promise<Song[]> { return this.actor.getSongs(); }
    async addSong(song: Song): Promise<void> { return this.actor.addSong(song); }
    async deleteSong(id: string): Promise<void> { return this.actor.deleteSong(id); }
    async getAlbums(): Promise<Album[]> { return this.actor.getAlbums(); }
    async addAlbum(album: Album): Promise<void> { return this.actor.addAlbum(album); }
    async deleteAlbum(id: string): Promise<void> { return this.actor.deleteAlbum(id); }
    async getSocialProfiles(): Promise<SocialProfile[]> { return this.actor.getSocialProfiles(); }
    async addSocialProfile(profile: SocialProfile): Promise<void> { return this.actor.addSocialProfile(profile); }
    async updateSocialProfile(profile: SocialProfile): Promise<void> { return this.actor.updateSocialProfile(profile); }
    async deleteSocialProfile(id: string): Promise<void> { return this.actor.deleteSocialProfile(id); }
    async getLiveUrl(): Promise<string> { return this.actor.getLiveUrl(); }
    async setLiveUrl(url: string): Promise<void> { return this.actor.setLiveUrl(url); }
    async clearLiveUrl(): Promise<void> { return this.actor.clearLiveUrl(); }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
